language: go

go:
  - 1.7.4
env:

before_install:
  - mkdir -p $GOPATH/src/github.com/lxn
  - cd $GOPATH/src/github.com/lxn
  - git clone https://github.com/lxn/walk.git
  - cd walk
  - go build
install:
  - cd $GOPATH/src/github.com/tinycedar/lily
  - go build -ldflags="-H windowsgui"
before_script:

after_script:

script:
